package DCMSCorba;


/**
* DcmsApp/DcmsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dcms.idl
* Wednesday, 25 July, 2018 11:10:23 PM EDT
*/

public interface DCMSInterfaceOperations 
{
  String createTRecord (String managerID, String teacher);
  String createSRecord (String managerID, String student);
  String getRecordCount (String managerID);
  String editRecord (String managerID, String recordID, String fieldname, String newvalue);
  String transferRecord (String managerID, String recordID, String location);
  String killServer (String location);
} // interface DcmsOperations
