package DCMSCorba;


/**
* DcmsApp/Dcms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dcms.idl
* Wednesday, 25 July, 2018 11:10:23 PM EDT
*/

public interface DCMSInterface extends DCMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcms
